### ISSUE TITLE
Helping with maintaining the collection

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-community/ansible-nomad#180]
Hello together,

my team is a frequent user of the community-roles [ansible-nomad](https://github.com/ansible-community/ansible-nomad) and [ansible-consul](https://github.com/ansible-community/ansible-consul).

Seeing that the last commits are very old (>6 months and >2 years), we'd like to help maintaining these roles.

@lanefu and @nre-ableton, it seems you merged PRs in these repos. Do you need any help?

**Comment by lanefu** [comment]
Yes let's figure out how to get you added.

**Comment by lanefu** [comment]
@rndmh3ro 

I've added you as a maintainer to the nomad and console repos.   Thanks for reaching out.

Background on how things decayed:

* Putting the roles under the Ansible community org was a bit of a mistake since the org admins didn't want  to allow whatever was needed to re-integrate these roles into Ansible galaxy unless it was a collection.   The vault role folks didn't want to switch to a collection.
* I really struggled to tune my GitHub notifications and really missed a lot of issues and PRs from these repos
* Currently decommissioning nomad in my own use cases

**Comment by rndmh3ro** [comment]
Thanks @lanefu!

Would it be possible to also add @beechesII as maintainer? He's one of our people running our internal nomad clusters and most familiar with them (I'm more familar with Ansible and it's whole processes).

As for the background: that's totally fine and undertandable to me, no worries! :)

**Comment by lanefu** [comment]
> Would it be possible to also add @beechesII as maintainer? He's one of our people running our internal nomad clusters and most familiar with them (I'm more familar with Ansible and it's whole processes).

Done!

**Comment by beechesII** [comment]
Thanks @lanefu :)

**Comment by nre-ableton** [comment]
@rndmh3ro If you're still interested in helping out with `ansible-consul`, then @bbaassssiiee is the one to talk to about that. However, that role is in a difficult position now given that CI is broken on account of the unconventional role name, which prevents us from merging any PRs (unless we want to hold our noses and ignore CI, which I would prefer not to). Anyways, that's an orthogonal topic, but I just mean to say that while maintenance help would be appreciated there, the repo isn't moving forward very much on account of that.

**Comment by maciej-lech** [comment]
@rndmh3ro are you still maintaining this repo?

**Comment by rndmh3ro** [comment]
> [@rndmh3ro](https://github.com/rndmh3ro) are you still maintaining this repo?

Sorr,y, no.
